// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: acmserver.proto

package acmserverpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data   []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Format string `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_acmserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_acmserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_acmserver_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Config) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type GetLatestRawConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLatestRawConfigRequest) Reset() {
	*x = GetLatestRawConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_acmserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLatestRawConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestRawConfigRequest) ProtoMessage() {}

func (x *GetLatestRawConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acmserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestRawConfigRequest.ProtoReflect.Descriptor instead.
func (*GetLatestRawConfigRequest) Descriptor() ([]byte, []int) {
	return file_acmserver_proto_rawDescGZIP(), []int{1}
}

type GetLatestRawConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLatestRawConfigResponse) Reset() {
	*x = GetLatestRawConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_acmserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLatestRawConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestRawConfigResponse) ProtoMessage() {}

func (x *GetLatestRawConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acmserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestRawConfigResponse.ProtoReflect.Descriptor instead.
func (*GetLatestRawConfigResponse) Descriptor() ([]byte, []int) {
	return file_acmserver_proto_rawDescGZIP(), []int{2}
}

type SaveRawConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaveRawConfigRequest) Reset() {
	*x = SaveRawConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_acmserver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveRawConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRawConfigRequest) ProtoMessage() {}

func (x *SaveRawConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acmserver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRawConfigRequest.ProtoReflect.Descriptor instead.
func (*SaveRawConfigRequest) Descriptor() ([]byte, []int) {
	return file_acmserver_proto_rawDescGZIP(), []int{3}
}

type SaveRawConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaveRawConfigResponse) Reset() {
	*x = SaveRawConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_acmserver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveRawConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRawConfigResponse) ProtoMessage() {}

func (x *SaveRawConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acmserver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRawConfigResponse.ProtoReflect.Descriptor instead.
func (*SaveRawConfigResponse) Descriptor() ([]byte, []int) {
	return file_acmserver_proto_rawDescGZIP(), []int{4}
}

type ListRawConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListRawConfigRequest) Reset() {
	*x = ListRawConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_acmserver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRawConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRawConfigRequest) ProtoMessage() {}

func (x *ListRawConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acmserver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRawConfigRequest.ProtoReflect.Descriptor instead.
func (*ListRawConfigRequest) Descriptor() ([]byte, []int) {
	return file_acmserver_proto_rawDescGZIP(), []int{5}
}

type ListRawConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListRawConfigResponse) Reset() {
	*x = ListRawConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_acmserver_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRawConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRawConfigResponse) ProtoMessage() {}

func (x *ListRawConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acmserver_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRawConfigResponse.ProtoReflect.Descriptor instead.
func (*ListRawConfigResponse) Descriptor() ([]byte, []int) {
	return file_acmserver_proto_rawDescGZIP(), []int{6}
}

var File_acmserver_proto protoreflect.FileDescriptor

var file_acmserver_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x63, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x61, 0x63, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x70, 0x62, 0x22, 0x34,
	0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73,
	0x74, 0x52, 0x61, 0x77, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x52, 0x61,
	0x77, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x16, 0x0a, 0x14, 0x53, 0x61, 0x76, 0x65, 0x52, 0x61, 0x77, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x61, 0x76, 0x65, 0x52,
	0x61, 0x77, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x16, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x61, 0x77, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x61, 0x77, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0x99, 0x02, 0x0a, 0x03, 0x41, 0x43, 0x4d, 0x12, 0x64, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x26, 0x2e, 0x61,
	0x63, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61,
	0x74, 0x65, 0x73, 0x74, 0x52, 0x61, 0x77, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x61, 0x63, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x52, 0x61, 0x77, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x55, 0x0a, 0x0a, 0x53, 0x61, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x21, 0x2e,
	0x61, 0x63, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x53, 0x61, 0x76, 0x65,
	0x52, 0x61, 0x77, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x22, 0x2e, 0x61, 0x63, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x53,
	0x61, 0x76, 0x65, 0x52, 0x61, 0x77, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x21, 0x2e, 0x61, 0x63, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x61, 0x77, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x63, 0x6d, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x61, 0x77, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x36, 0x5a,
	0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4c, 0x75, 0x6e, 0x61,
	0x72, 0x68, 0x61, 0x6c, 0x6f, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x61, 0x63, 0x6d, 0x2f, 0x61, 0x63,
	0x6d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x70, 0x62, 0x3b, 0x61, 0x63, 0x6d, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_acmserver_proto_rawDescOnce sync.Once
	file_acmserver_proto_rawDescData = file_acmserver_proto_rawDesc
)

func file_acmserver_proto_rawDescGZIP() []byte {
	file_acmserver_proto_rawDescOnce.Do(func() {
		file_acmserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_acmserver_proto_rawDescData)
	})
	return file_acmserver_proto_rawDescData
}

var file_acmserver_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_acmserver_proto_goTypes = []interface{}{
	(*Config)(nil),                     // 0: acmserverpb.Config
	(*GetLatestRawConfigRequest)(nil),  // 1: acmserverpb.GetLatestRawConfigRequest
	(*GetLatestRawConfigResponse)(nil), // 2: acmserverpb.GetLatestRawConfigResponse
	(*SaveRawConfigRequest)(nil),       // 3: acmserverpb.SaveRawConfigRequest
	(*SaveRawConfigResponse)(nil),      // 4: acmserverpb.SaveRawConfigResponse
	(*ListRawConfigRequest)(nil),       // 5: acmserverpb.ListRawConfigRequest
	(*ListRawConfigResponse)(nil),      // 6: acmserverpb.ListRawConfigResponse
}
var file_acmserver_proto_depIdxs = []int32{
	1, // 0: acmserverpb.ACM.GetLatestConfig:input_type -> acmserverpb.GetLatestRawConfigRequest
	3, // 1: acmserverpb.ACM.SaveConfig:input_type -> acmserverpb.SaveRawConfigRequest
	5, // 2: acmserverpb.ACM.ListConfig:input_type -> acmserverpb.ListRawConfigRequest
	2, // 3: acmserverpb.ACM.GetLatestConfig:output_type -> acmserverpb.GetLatestRawConfigResponse
	4, // 4: acmserverpb.ACM.SaveConfig:output_type -> acmserverpb.SaveRawConfigResponse
	6, // 5: acmserverpb.ACM.ListConfig:output_type -> acmserverpb.ListRawConfigResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_acmserver_proto_init() }
func file_acmserver_proto_init() {
	if File_acmserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_acmserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_acmserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLatestRawConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_acmserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLatestRawConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_acmserver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveRawConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_acmserver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveRawConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_acmserver_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRawConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_acmserver_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRawConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_acmserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_acmserver_proto_goTypes,
		DependencyIndexes: file_acmserver_proto_depIdxs,
		MessageInfos:      file_acmserver_proto_msgTypes,
	}.Build()
	File_acmserver_proto = out.File
	file_acmserver_proto_rawDesc = nil
	file_acmserver_proto_goTypes = nil
	file_acmserver_proto_depIdxs = nil
}
